

const Imported_save = {}

const Start_save = {
    Player : {
        name : null,
        class : null,
        lvl : 0,
        exp : 0,
        hp : 100,
        ap : 100,
        location : 'Test1',
        position_x : 3,
        position_y : 3,
    },
    Locations : {
        Test1 : {
            background_map : [  ['.', 'x10/f', '.'],
                                ['x12/f'],
                                ['x12/f'],
                                ['x12/f'],
                                ['x12/f'],
                                ['.', 'x10/f', '.'],
            ],
            walls_map : [       ['n', 'x10/w', 'n'],
                                ['w', 'x10/n', 'w'],
                                ['w', 'x5/n', 'w', 'x4/n', 'w'],
                                ['w', 'x10/n', 'ls'],
                                ['w', 'x10/n', 'w'],
                                ['n', 'x10/w', 'n'],
            ],
            collision_map : [   ['.', 'x10/a', '.'],
                                ['a', 'x10/.', 'a'],
                                ['a', 'x5/.', 'url', 'x4/.', 'a'],
                                ['a', 'x10/.', '.-s:1:3:Test2'],
                                ['a', 'x10/.', 'a'],
                                ['.', 'x10/a', '.'],
            ],
            items : null,
            creatures : null,
        },
        Test2 : {
            background_map : [  ['x20/f'], 
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'], 
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
                                ['x20/f'],
            ],
            walls_map : [       ['w'],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
            ],
            collision_map : [   [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
                                [],
            ],
            items : null,
            creatures : null,
        }
    }
}